grails-app/domain/com/askoverflow/Tag.groovy
package com.askoverflow

class Tag
{
    String description;

    public String toString()
    {
        return description;
    }

    static hasMany = [questions:Question];
    static belongsTo = Question;

    static constraints = {
        description size: 3..15, blank: false, unique: true
    }
}

grails-app/controllers/com/askoverflow/BadgeController.groovy
package com.askoverflow



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BadgeController
{
    static Boolean linkMe = false;
    static allowedMethods = [list: "GET"]

    def index(Integer max)
    {
        respond Badge.list(), model:[badgeInstanceCount: Badge.count()]
    }
}

grails-app/controllers/com/askoverflow/TagController.groovy
package com.askoverflow



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController
{
    static Boolean linkMe = true;
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max)
    {
        respond Tag.list(), model:[tagInstanceCount: Tag.count()]
    }

    def show(Tag tagInstance) {
        respond tagInstance
    }

    def create() {
        respond new Tag(params)
    }

    @Transactional
    def save(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'tag.created.message', default: 'Tag created !')
                redirect tagInstance
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance)
    {
        render(template: "update", bean: tagInstance, var:"tagInstance");
    }

    @Transactional
    def update(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'tag.updated.message', default: 'Tag updated !')
                redirect tagInstance
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

    def deleteTagService;

    @Transactional
    def delete(Tag tagInstance) {

        if (tagInstance == null) {
            notFound()
            return
        }

        // check that there is no question linked with the tag
        if (deleteTagService.tagHasNoQuestion(tagInstance))
        {
            tagInstance.delete flush:true

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'tag.deleted.message', default: 'Tag deleted !')
                    redirect action:"index", method:"GET"
                }
                '*'{ render status: NO_CONTENT }
            }
        }
        else
        {
            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'tag.cant.be.deleted.message', default: 'Tag cannot be deleted !')
                    redirect tagInstance
                }
                '*'{ render status: NO_CONTENT }
            }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tag.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tag/_form.gsp
<%@ page import="com.askoverflow.Tag" %>



<div class="fieldcontain ${hasErrors(bean: tagInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="tag.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" maxlength="15" required="" value="${tagInstance?.description}"/>

</div>

grails-app/views/tag/_update.gsp
<%@ page import="com.askoverflow.Tag" %>

<h1><g:message code="tag.edit.label" default="Edit the tag" /></h1>
            
<g:hasErrors bean="${tagInstance}">
<ul class="errors" role="alert">
    <g:eachError bean="${tagInstance}" var="error">
    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
    </g:eachError>
</ul>
</g:hasErrors>
<g:form url="[resource:tagInstance, action:'update']" method="PUT" >
    <g:hiddenField name="version" value="${tagInstance?.version}" />
    <fieldset class="form">
        <g:render template="form"/>
    </fieldset>
    <fieldset class="buttons">
        <g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
    </fieldset>
</g:form>

grails-app/views/tag/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="tag.create.label" default="Create a tag" /> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#create-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>
				
				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="create-tag" class="content scaffold-create" role="main">
			
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<h1><g:message code="tag.create.label" default="Create a tag" /></h1>
			
			<g:hasErrors bean="${tagInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${tagInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:tagInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/tag/index.gsp
<%@ page import="com.askoverflow.Tag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="tag.list.label" default="Tag list" /> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#list-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<li><g:link class="create" controller="question" action="create"><g:message code="question.new.label" default="Ask a question" /></g:link></li>

				<sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_MODERATOR">
					<li><g:link class="create" action="create"><g:message code="tag.new.label" default="New tag" /></g:link></li>
				</sec:ifAnyGranted>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="list-tag" class="content scaffold-list" role="main">
			<h1><g:message code="tag.list.label" default="Tag list" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<th><g:message code="tag.description.label" default="Description" /></th>

						<th><g:message code="tag.popularity.label" default="Popularity" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${tagInstanceList}" status="i" var="tagInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${tagInstance.id}">${fieldValue(bean: tagInstance, field: "description")}</g:link></td>

						<td>${tagInstance?.questions.size()}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${tagInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/tag/show.gsp
<%@ page import="com.askoverflow.Tag" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'tag.label', default: 'Tag')}" />
		<title><g:message code="tag.show.label" default="Show the tag" /> : <g:fieldValue bean="${tagInstance}" field="description"/> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#show-tag" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<li><g:link class="create" controller="question" action="create"><g:message code="question.new.label" default="Ask a question" /></g:link></li>

				<sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_MODERATOR">
					<li><g:link class="create" action="create"><g:message code="tag.new.label" default="New tag" /></g:link></li>
				</sec:ifAnyGranted>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="show-tag" class="content scaffold-show" role="main">
			
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<div id="tag_${tagInstance.id}">

				<h1><g:message code="tag.show.label" default="Show the tag" /></h1>

				<table class="tag">
		        <tbody>
		        <tr class="tag-tr">
		            <td class="tagcell">    
						<div class="tag">

							<span id="description-label" class="property-label"><g:message code="tag.description.label" default="Description" /></span>
						
							<span class="property-value" aria-labelledby="description-label"><div><g:fieldValue bean="${tagInstance}" field="description"/></div></span>

						</div>
		            </td>
		            
					<td class="infocell">

						<table class="tag">
						<tbody>
						<tr class="tag-tr">
							<td class="listcell">
								<div class="listhead">

									<span id="questions-count" class="property-label">${tagInstance?.questions.size()}</span>

									<span id="questions-label" class="property-label"><g:message code="tag.questions.label" default="Questions" /></span>

								</div>
							</td>
						</tr>
						<tr class="tag-tr">
							<td class="listcell">
								<table class="tag">
								<tbody>
								<g:each in="${tagInstance.questions}" var="q">
									<tr class="tag-tr">

										<td class="listvotecell"><span class="property-value" aria-labelledby="questions-label"><g:fieldValue bean="${q}" field="vote"/></span>
										</td>

										<td class="listtextcell"><span class="property-value" aria-labelledby="questions-label"><g:link controller="question" action="show" id="${q.id}">${q?.truncateToString(50).encodeAsHTML()}</g:link></span>
										</td>
									</tr>
								</g:each>
								</tbody>
								</table>
							</td>
						</tr>
						</tbody>
						</table>
					</td>
				</tr>
				</tbody>
				</table>

				<g:form url="[resource:tagInstance, action:'delete']" method="DELETE">
					<fieldset class="buttons">
						<g:remoteLink class="edit" action="edit" resource="${tagInstance}" update="[success: "tag_${tagInstance.id}"]"><g:message code="default.button.edit.label" default="Edit" /></g:remoteLink>

						<g:if test="${tagInstance.questions.size() == 0}">
							<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
						</g:if>
					</fieldset>
				</g:form>
			</div>
		</div>
	</body>
</html>