grails-app/domain/com/askoverflow/Role.groovy
package com.askoverflow

class Role
{
	String authority;
    String name;

    public String toString()
    {
        return name;
    }

    Set<User> getUsers()
    {
        UserRole.findAllByRole(this).collect { it.user }
    }

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
        name size: 5..15, blank: false, unique: true
	}
}

grails-app/controllers/com/askoverflow/BadgeController.groovy
package com.askoverflow



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BadgeController
{
    static Boolean linkMe = false;
    static allowedMethods = [list: "GET"]

    def index(Integer max)
    {
        respond Badge.list(), model:[badgeInstanceCount: Badge.count()]
    }
}

grails-app/controllers/com/askoverflow/RoleController.groovy
package com.askoverflow



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RoleController
{
    static Boolean linkMe = true;
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max)
    {
        respond Role.list(), model:[roleInstanceCount: Role.count()]
    }

    def show(Role roleInstance) {
        respond roleInstance
    }

    def create() {
        respond new Role(params)
    }

    @Transactional
    def save(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'create'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'role.created.message', default: 'Role created !')
                redirect roleInstance
            }
            '*' { respond roleInstance, [status: CREATED] }
        }
    }

    def edit(Role roleInstance)
    {
        render(template: "update", bean: roleInstance, var:"roleInstance");
    }

    @Transactional
    def update(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'edit'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'role.updated.message', default: 'Role updated !')
                redirect roleInstance
            }
            '*'{ respond roleInstance, [status: OK] }
        }
    }

    def deleteRoleService;

    @Transactional
    def delete(Role roleInstance) {

        if (roleInstance == null) {
            notFound()
            return
        }

        // update user's authority for users with this role
        deleteRoleService.deleteUserAssociation(roleInstance);

        roleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'role.deleted.message', default: 'Role deleted !')
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'role.label', default: 'Role'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/role/_form.gsp
<%@ page import="com.askoverflow.Role" %>


<div class="fieldcontain ${hasErrors(bean: roleInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="role.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" maxlength="15" required="" value="${roleInstance?.name}"/>

</div>

<g:hiddenField id="authority" name="authority" value="${roleInstance?.authority}" />

grails-app/views/role/_update.gsp
<%@ page import="com.askoverflow.Role" %>

<h1><g:message code="role.edit.label" default="Edit the role" /></h1>
            
<g:hasErrors bean="${roleInstance}">
<ul class="errors" role="alert">
    <g:eachError bean="${roleInstance}" var="error">
    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
    </g:eachError>
</ul>
</g:hasErrors>
<g:form url="[resource:roleInstance, action:'update']" method="PUT" >
    <g:hiddenField name="version" value="${roleInstance?.version}" />
    <fieldset class="form">
        <g:render template="form"/>
    </fieldset>
    <fieldset class="buttons">
        <g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
    </fieldset>
</g:form>

grails-app/views/role/index.gsp
<%@ page import="com.askoverflow.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title><g:message code="role.list.label" default="Role list" /> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#list-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<sec:ifAllGranted roles="ROLE_ADMIN">
					<li><g:link elementId="userRoleButton" class="list" controller="userRole" action="index"><g:message code="userRole.list.label" default="UserRole list" /></g:link></li>
				</sec:ifAllGranted>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="list-role" class="content scaffold-list" role="main">
			<h1><g:message code="role.list.label" default="Role list" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<th><g:message code="role.name.label" default="Name" /></th>

						<th><g:message code="role.popularity.label" default="Popularity" /></th>

					</tr>
				</thead>
				<tbody>
				<g:each in="${roleInstanceList}" status="i" var="roleInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${roleInstance.id}">${fieldValue(bean: roleInstance, field: "name")}</g:link></td>

						<td>${roleInstance?.getUsers().size()}</td>

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${roleInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/role/show.gsp
<%@ page import="com.askoverflow.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title><g:message code="role.show.label" default="Show role" /> : <g:fieldValue bean="${roleInstance}" field="name"/> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#show-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<sec:ifAllGranted roles="ROLE_ADMIN">
					<li><g:link elementId="roleButton" class="list" action="index"><g:message code="role.list.label" default="Role list" /></g:link></li>

					<li><g:link elementId="userRoleButton" class="list" controller="userRole" action="index"><g:message code="userRole.list.label" default="UserRole list" /></g:link></li>
				</sec:ifAllGranted>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="show-role" class="content scaffold-show" role="main">
		
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<div id="role_${roleInstance.id}">

				<h1><g:message code="role.show.label" default="Show role" /></h1>

				<table class="role">
		        <tbody>
		        <tr class="role-tr">
		            <td class="rolecell">    
						<div class="role">

							<span id="description-label" class="property-label"><g:message code="role.name.label" default="Name" /></span>
						
							<span class="property-value" aria-labelledby="description-label"><div><g:fieldValue bean="${roleInstance}" field="name"/></div></span>

						</div>
		            </td>
		            
					<td class="infocell">

						<table class="role">
						<tbody>
						<tr class="role-tr">
							<td class="listcell">
								<div class="listhead">

									<span id="questions-count" class="property-label">${roleInstance?.users.size()}</span>

									<span id="questions-label" class="property-label"><g:message code="role.users.label" default="Users" /></span>

								</div>
							</td>
						</tr>
						<tr class="role-tr">
							<td class="listcell">
								<table class="role">
								<tbody>
								<g:each in="${roleInstance.users}" var="u">
									<tr class="role-tr">

										<td class="listvotecell"><span class="property-value" aria-labelledby="user-label"><g:fieldValue bean="${u}" field="reputation"/></span>
										</td>

										<td class="listtextcell"><span class="property-value" aria-labelledby="user-label"><g:link controller="user" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></span>
										</td>
									</tr>
								</g:each>
								</tbody>
								</table>
							</td>
						</tr>
						</tbody>
						</table>
					</td>
				</tr>
				</tbody>
				</table>

				<g:form url="[resource:roleInstance, action:'delete']" method="DELETE">
					<fieldset class="buttons">
						<sec:ifAllGranted roles="ROLE_ADMIN">
							<g:remoteLink class="edit" action="edit" resource="${roleInstance}" update="[success: "role_${roleInstance.id}"]"><g:message code="default.button.edit.label" default="Edit" /></g:remoteLink>
						</sec:ifAllGranted>
					</fieldset>
				</g:form>
			</div>
		</div>
	</body>
</html>