grails-app/domain/com/askoverflow/Answer.groovy
package com.askoverflow

class Answer extends Post
{
    public String toString()
    {
        return content;
    }

    static belongsTo = [question:Question]

    static constraints = {
    }
}

grails-app/controllers/com/askoverflow/AnswerController.groovy
package com.askoverflow



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AnswerController
{
    static Boolean linkMe = true;
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE", downVote: "POST", upVote: "POST"]

    def index(Integer max)
    {
        respond Answer.list(sort: "vote", order: "desc"), model:[answerInstanceCount: Answer.count()]
    }

    def show(Answer answerInstance) {
        respond answerInstance
    }

    def create()
    {
        def newAnswer = new Answer(params);
        render(template: "new", bean: newAnswer, var:"answerInstance");
    }

    def badgeService;

    @Transactional
    def save(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'create'
            return
        }

        answerInstance.save flush:true

        // badge check for the author
        badgeService.checkForBadges(answerInstance.author);

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'answer.created.message', default: 'Answer created')
                redirect answerInstance.question
            }
            '*' { respond answerInstance, [status: CREATED] }
        }
    }

    def edit(Answer answerInstance)
    {
        render(template: "update", bean: answerInstance, var:"answerInstance");
    }

    @Transactional
    def update(Answer answerInstance) {
        if (answerInstance == null) {
            notFound()
            return
        }

        if (answerInstance.hasErrors()) {
            respond answerInstance.errors, view:'edit'
            return
        }

        answerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'answer.updated.message', default: 'Answer updated !')
                redirect answerInstance.question
            }
            '*'{ respond answerInstance, [status: OK] }
        }
    }

    def deleteAnswerService;

    @Transactional
    def delete(Answer answerInstance) {

        if (answerInstance == null) {
            notFound()
            return
        }

        // delete vote associations ans update author's reputation
        deleteAnswerService.updateVoteAndAuthorOnAnswerDelete(answerInstance);

        // question recuperation for the redirection
        Question redirectQuestion = answerInstance.question;

        answerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'anwser.deleted.message', default: 'Answer deleted !')
                redirect redirectQuestion
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def downVoteService;
    def upVoteService;

    @Transactional
    def upVote(Answer answerInstance)
    {
        // security verification - not same user
        String loggedUserId = sec.loggedInUserInfo(field: 'id').toString();
        if (answerInstance.author.id.toString() != loggedUserId)
        {
            upVoteService.upVoteAnswer(answerInstance, Long.parseLong(loggedUserId));
            render answerInstance.vote;
        }
    }

    @Transactional
    def downVote(Answer answerInstance)
    {
        // security verification - not same user
        String loggedUserId = sec.loggedInUserInfo(field: 'id').toString();
        if (answerInstance.author.id.toString() != loggedUserId)
        {
            downVoteService.downVoteAnswer(answerInstance, Long.parseLong(loggedUserId));
            render answerInstance.vote;
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'answer.label', default: 'Answer'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/answer/_form.gsp
<%@ page import="com.askoverflow.Answer" %>



<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'content', 'error')} required">
	<label for="content">
		<g:message code="answer.content.label" default="Content" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="content" required="" value="${answerInstance?.content}"/>

</div>

<g:hiddenField id="author" name="author.id" value="${sec.loggedInUserInfo(field: 'id')}" class="many-to-one" />

<g:hiddenField id="question" name="question.id" value="${answerInstance?.question?.id}" class="many-to-one" />

grails-app/views/answer/_formEdit.gsp
<%@ page import="com.askoverflow.Answer" %>



<div class="fieldcontain ${hasErrors(bean: answerInstance, field: 'content', 'error')} required">
    <label for="content">
        <g:message code="answer.content.label" default="Content" />
        <span class="required-indicator">*</span>
    </label>
    <g:textArea name="content" required="" value="${answerInstance?.content}"/>

</div>

<g:hiddenField id="author" name="author.id" value="${answerInstance?.author.id}" class="many-to-one" />

<g:hiddenField id="question" name="question.id" value="${answerInstance?.question?.id}" class="many-to-one" />

grails-app/views/answer/_new.gsp
<%@ page import="com.askoverflow.Answer" %>


<h1><g:message code="answer.create.label" default="Create an answer" /></h1>

<g:hasErrors bean="${answerInstance}">
<ul class="errors" role="alert">
    <g:eachError bean="${answerInstance}" var="error">
    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
    </g:eachError>
</ul>
</g:hasErrors>
<g:form url="[resource:answerInstance, action:'save']" >
    <fieldset class="form">
        <g:render template="form"/>
    </fieldset>
    <fieldset class="buttons">
        <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
    </fieldset>
</g:form>

grails-app/views/answer/_update.gsp
<%@ page import="com.askoverflow.Answer" %>

<h1><g:message code="answer.edit.label" default="Edit the answer" /></h1>

<g:hasErrors bean="${answerInstance}">
<ul class="errors" role="alert">
    <g:eachError bean="${answerInstance}" var="error">
    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
    </g:eachError>
</ul>
</g:hasErrors>
<g:form url="[resource:answerInstance, action:'update']" method="PUT" >
    <g:hiddenField name="version" value="${answerInstance?.version}" />
    <fieldset class="form">
        <g:render template="formEdit"/>
    </fieldset>
    <fieldset class="buttons">
        <g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
    </fieldset>
</g:form>

grails-app/views/answer/_view.gsp
<%@ page import="com.askoverflow.Answer" %>


<div id="answer_${answerInstance.id}">
    <table class="post">
    <tbody>
    <tr class="post-tr">
        <td class="votecell">    
            <div class="vote">
                <span id="tags-label" class="property-label"><g:message code="answer.vote.label" default="Vote" /></span>

                <span class="property-value" aria-labelledby="vote-label"><div id="result_answer_${answerInstance.id}">${answerInstance.vote}</div></span>
            </div>
        </td>
        
        <td class="answercell">
            <div class="posttext">
                <span class="property-value" aria-labelledby="content-label"><g:fieldValue bean="${answerInstance}" field="content"/></span>
            </div>
            <table class="postinfo">
            <tbody>
            <tr class="post-tr">
                <td class="infocell">
                    <span id="tags-label" class="property-label"><g:message code="answer.author.label" default="Author" /> : </span>

                    <span class="property-value" aria-labelledby="author-label"><g:link controller="user" action="show" id="${answerInstance?.author?.id}">${answerInstance?.author?.encodeAsHTML()}</g:link></span>
                </td>
                <td class="infocell">
                    <span class="property-value" aria-labelledby="publicationDate-label"><g:formatDate date="${answerInstance?.publicationDate}" /></span>
                </td>
            </tr>
            </tbody>
            </table>
        </td>
    </tr>
    </tbody>
    </table>

    <g:form url="[resource:answerInstance, controller:'answer', action:'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:remoteLink class="upvote" controller="answer" action="upVote" id="${answerInstance.id}" update="[success: "result_answer_${answerInstance.id}"]"><g:message code="default.button.upVote.label" default="UpVote" /></g:remoteLink>

            <g:remoteLink class="downvote" controller="answer" action="downVote" id="${answerInstance.id}" update="[success: "result_answer_${answerInstance.id}"]"><g:message code="default.button.downVote.label" default="DownVote" /></g:remoteLink>

            <sec:ifAnyGranted roles="ROLE_ADMIN,ROLE_MODERATOR">
                <g:remoteLink class="edit" controller="answer" action="edit" resource="${answerInstance}" update="[success: "answer_${answerInstance.id}"]"><g:message code="default.button.edit.label" default="Edit" /></g:remoteLink>

                <g:actionSubmit class="delete" controller="answer" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </sec:ifAnyGranted> 
        </fieldset>
    </g:form>
</div>

grails-app/views/answer/index.gsp
<%@ page import="com.askoverflow.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="answer.list.label" default="Answer list" /> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#list-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<sec:ifAllGranted roles="ROLE_ADMIN">
                    <li><g:link elementId="roleButton" class="list" controller="role" action="index"><g:message code="role.list.label" default="Role list" /></g:link></li>
                </sec:ifAllGranted>

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="list-answer" class="content scaffold-list" role="main">
			<h1><g:message code="answer.list.label" default="Answer list" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>

						<th><g:message code="answer.vote.label" default="Vote" /></th>

						<th><g:message code="answer.publicationDate.label" default="Publication Date" /></th>

						<th><g:message code="answer.content.label" default="Content" /></th>

						<th><g:message code="answer.author.label" default="Author" /></th>

						<th><g:message code="answer.question.label" default="Question" /></th>

					</tr>
				</thead>
				<tbody>
				<g:each in="${answerInstanceList}" status="i" var="answerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td>${fieldValue(bean: answerInstance, field: "vote")}</td>

						<td><g:link action="show" id="${answerInstance.id}">${answerInstance?.truncateToString(20).encodeAsHTML()}</g:link></td>
					
						<td>${fieldValue(bean: answerInstance, field: "question")}</td>
						
						<td>${fieldValue(bean: answerInstance, field: "author")}</td>

						<td><g:formatDate date="${answerInstance.publicationDate}" /></td>
										
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${answerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/answer/show.gsp
<%@ page import="com.askoverflow.Answer" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'answer.label', default: 'Answer')}" />
		<title><g:message code="answer.show.label" default="Show the answer" /> - Ask Over Flow</title>
	</head>
	<body>
		<a href="#show-answer" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>

				<li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

				<li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

				<li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

				<sec:ifAllGranted roles="ROLE_ADMIN">
                    <li><g:link elementId="roleButton" class="list" controller="role" action="index"><g:message code="role.list.label" default="Role list" /></g:link></li>

                    <li><g:link elementId="answerButton" class="list" action="index"><g:message code="answer.list.label" default="Answer list" /></g:link></li>
                </sec:ifAllGranted>				

				<sec:ifLoggedIn>
					<li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
				</sec:ifLoggedIn>
			</ul>
		</div>
		<div id="show-answer" class="content scaffold-show" role="main">
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<h1><g:message code="answer.show.label" default="Show the answer" /></h1>
			<g:render template="view"/>
		</div>
	</body>
</html>