grails-app/domain/com/askoverflow/User.groovy
package com.askoverflow

class User
{
	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired = false
	boolean accountLocked = false
	boolean passwordExpired = false
	String email;
    int reputation = 0;
    Date incriptionDate = new Date();

    static hasMany = [questions:Question, answers:Answer];

	static transients = ['springSecurityService']

	static constraints = {
		username size: 3..10, blank: false, unique: true
		password size: 5..500, blank: false
		email email: true, blank: false, unique:true
	}

	static mapping = {
		password column: '`password`'
		questions sort:'vote', order:'desc'
        answers sort:'vote', order:'desc'
	}

	public String toString()
    {
        return username;
    }

    public void upReputation()
    {
        reputation++;
    }

    public void downReputation()
    {
        reputation--;
    }

    public void updateReputation(int reputationToBeDeleted)
    {
        reputation -= reputationToBeDeleted;
    }

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}

    Set<Badge> getEarnedBadges() {
        EarnedBadge.findAllByUser(this).collect { it.badge }
    }
}

grails-app/domain/com/askoverflow/UserRole.groovy
package com.askoverflow

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

	private static final long serialVersionUID = 1

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
		other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.get()
	}

	static boolean exists(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.count() > 0
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		def instance = new UserRole(user: user, role: role)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(User u, Role r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UserRole.where {
			user == User.load(u.id) &&
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(User u, boolean flush = false) {
		if (u == null) return

		UserRole.where {
			user == User.load(u.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static void removeAll(Role r, boolean flush = false) {
		if (r == null) return

		UserRole.where {
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static constraints = {
		role validator: { Role r, UserRole ur ->
			if (ur.user == null) return
			boolean existing = false
			UserRole.withNewSession {
				existing = UserRole.exists(ur.user.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

grails-app/controllers/com/askoverflow/UserRoleController.groovy
package com.askoverflow


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserRoleController
{
    static Boolean linkMe = true;
    static allowedMethods = [save: "POST", delete: "DELETE"]

    def index(Integer max)
    {
        respond UserRole.list(), model:[userRoleInstanceCount: UserRole.count()]
    }

    def create() {
        respond new UserRole(params)
    }

    def badgeService;

    @Transactional
    def save(UserRole userRoleInstance) {

        if (userRoleInstance == null) {
            notFound()
            return
        }

        if (userRoleInstance.hasErrors()) {
            respond userRoleInstance.errors, view:'create'
            return
        }

        UserRole.create(userRoleInstance.user, userRoleInstance.role, true);

        // badge check for the concerned user
        badgeService.checkForBadges(userRoleInstance.user);

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'userRole.created.message', default: 'UserRole created !')
                redirect action: "index", method: "GET"
            }
            '*' { render status: CREATED }
        }
    }

    def userRoleService;

    @Transactional
    def delete(Long userId, Long roleId) {

        if (! UserRole.exists(userId, roleId)) {
            notFound()
            return
        }

        // last admin association delete control
        Role role = Role.findById(roleId);
        if (userRoleService.roleAssociationCanBeDeleted(role))
        {
            User concernedUser = User.findById(userId);
            UserRole.remove(concernedUser, role, true);

            // badge check for the concerned user
            badgeService.checkForBadges(concernedUser);

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'userRole.deleted.message', default: 'UserRole deleted !')
                    redirect action:"index", method:"GET"
                }
                '*'{ render status: NO_CONTENT }
            }
        }
        else
        {
            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'userRole.cant.be.deleted.message', default: 'UserRole can not be deleted !')
                    redirect action:"index", method:"GET"
                }
                '*'{ render status: NO_CONTENT }
            }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'userRole.label', default: 'UserRole'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/userRole/_form.gsp
<%@ page import="com.askoverflow.UserRole" %>


<div class="fieldcontain ${hasErrors(bean: userRoleInstance, field: 'user', 'error')} required">
    <label for="user">
        <g:message code="userRole.user.label" default="User" />
        <span class="required-indicator">*</span>
    </label>
    <g:select name="user" required="" from="${com.askoverflow.User.list()}" optionKey="id" value="${userRoleInstance?.user?.id}" />

</div>

<div class="fieldcontain ${hasErrors(bean: userRoleInstance, field: 'role', 'error')} required">
    <label for="role">
        <g:message code="userRole.role.label" default="Role" />
        <span class="required-indicator">*</span>
    </label>
    <g:select name="role" required="" from="${com.askoverflow.Role.list()}" optionKey="id" value="${userRoleInstance?.role?.id}" />

</div>

grails-app/views/userRole/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'userRole.label', default: 'UserRole')}" />
        <title><g:message code="userRole.create.label" default="Authorization creation" /> - Ask Over Flow</title>
    </head>
    <body>
        <a href="#create-userRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>
                
                <li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

                <li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

                <li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

                <sec:ifAllGranted roles="ROLE_ADMIN">
                    <li><g:link elementId="roleButton" class="list" controller="role" action="index"><g:message code="role.list.label" default="Role list" /></g:link></li>

                    <li><g:link elementId="userRoleButton" class="list" action="index"><g:message code="userRole.list.label" default="Authorization list" /></g:link></li>
                </sec:ifAllGranted>

                <sec:ifLoggedIn>
                    <li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
                </sec:ifLoggedIn>
            </ul>
        </div>
        <div id="create-userRole" class="content scaffold-create" role="main">
            
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>

            <h1><g:message code="userRole.create.label" default="Authorization creation" /></h1>
            
            <g:hasErrors bean="${userRoleInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${userRoleInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message code="userRole.not.unique.error"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form url="[resource:userRoleInstance, action:'save']" >
                <fieldset class="form">
                    <g:render template="form"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/userRole/index.gsp
<%@ page import="com.askoverflow.UserRole" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'userRole.label', default: 'UserRole')}" />
        <title><g:message code="userRole.list.label" default="UserRole list" /> - Ask Over Flow</title>
    </head>
    <body>
        <a href="#list-userRole" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link elementId="questionButton" class="list" controller="question" action="index"><g:message code="question.list.label" default="Question list" /></g:link></li>
                
                <li><g:link elementId="tagButton" class="list" controller="tag" action="index"><g:message code="tag.list.label" default="Tag list" /></g:link></li>

                <li><g:link elementId="badgeButton" class="list" controller="badge" action="index"><g:message code="badge.list.label" default="Badge list" /></g:link></li>

                <li><g:link elementId="userButton" class="list" controller="user" action="index"><g:message code="user.list.label" default="User list" /></g:link></li>

                <sec:ifAllGranted roles="ROLE_ADMIN">
                    <li><g:link elementId="roleButton" class="list" controller="role" action="index"><g:message code="role.list.label" default="Role list" /></g:link></li>

                    <li><g:link class="create" action="create"><g:message code="userRole.new.label" default="New authorization" /></g:link></li>
                </sec:ifAllGranted>

                <sec:ifLoggedIn>
                    <li><g:link elementId="profileButton" class="list" controller="user" action="show" id="${sec.loggedInUserInfo(field: 'id')}"><sec:username/></g:link></li>
                </sec:ifLoggedIn>
            </ul>
        </div>
        <div id="list-userRole" class="content scaffold-list" role="main">
            <h1><g:message code="userRole.list.label" default="UserRole list" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>

            <table>
            <thead>
                    <tr>
                    
                        <th><g:message code="userRole.user.label" default="User" /></th>

                        <th><g:message code="userRole.role.label" default="Role" /></th>

                        <th><g:message code="userRole.action.label" default="Actions" /></th>
                    
                    </tr>
                </thead>
                <tbody>
                <g:each in="${userRoleInstanceList}" status="i" var="userRoleInstance">
                    <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                    
                        <td>${fieldValue(bean: userRoleInstance, field: "user")}</td>
                    
                        <td>${fieldValue(bean: userRoleInstance, field: "role")}</td>

                        <td>
                            <g:form url="[action:'delete']" method="DELETE">

                                <g:hiddenField name="userId" value="${userRoleInstance.user.id}" />
                                <g:hiddenField name="roleId" value="${userRoleInstance.role.id}" />

                                <fieldset class="buttons">

                                <sec:ifAllGranted roles="ROLE_ADMIN">
                                    <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                                </sec:ifAllGranted>
                            </fieldset>
                        </g:form>
                        </td>
                    </tr>
                </g:each>
                </tbody>
            </table>
            <div class="pagination">
                <g:paginate total="${userInstanceCount ?: 0}" />
            </div>
        </div>
    </body>
</html>